version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: data_eng
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    
  spring-app:
    image: backend-pagnet:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/data_eng
    depends_on:
      - postgres-db

  spa-app:
    image: frontend-pagnet:latest
    ports:
      - "9090:9090" 
    depends_on:
      - spring-app